DROP TABLE IF EXISTS FACE_SECTION;
DROP TABLE IF EXISTS FACE_SECTION_DETAIL;
DROP TABLE IF EXISTS ADMIN;

CREATE TABLE ADMIN (
  USER_ID VARCHAR(50) PRIMARY KEY,
  PASSWORD VARCHAR(500),
  REG_DTS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MOD_DTS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (USER_ID)
);

CREATE TABLE FACE_SECTION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    SECTION_NAME VARCHAR(50),
    FS_CODE VARCHAR(7),
    REG_DTS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MOD_DTS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE TABLE FACE_SECTION_DETAIL (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    DETAIL_NAME VARCHAR(50),
    PRICE NUMBER(10),
    FS_CODE VARCHAR(7),
    REG_DTS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MOD_DTS TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);